name: Auto Update Fork

on:
  push:
    branches:
      - dev
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          repository: rickycse/Summer2026-Internships
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/vanshb03/Summer2026-Internships.git
          git fetch upstream
      
      - name: Set up Git user
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "actions@github.com"

      - name: Merge upstream changes
        run: |
          git fetch upstream dev
          git checkout -B dev origin/dev
          git merge upstream/dev
          git push origin dev

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install -r requirements.txt

      - name: Update MongoDB
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}  
        run: |
            python3 .github/scripts/update_mongo.py

      - name: Testing Secrets
        run: |
          echo "MONGO_COLLECTION: $MONGO_COLLECTION"

      - name: Clean up
        run: |
          git remote remove upstream